version: '2.2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elastic
    environment:
      - discovery.type=single-node
    ports: 
      - 9200:9200
    networks:
      - elastic
    volumes: 
      - D:/elasticsearch:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports: 
      - 5601:5601
    environment: 
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks: 
      - elastic

networks: 
  elastic:
    driver: bridge