using System;

namespace ElasticsearchIntro.Dtos
{
    public class FinancialStatement
    {
        public string OrganCode { get; set; }
        public int YearReport { get; set; }
        public DateTime? EndDate { get; set; }
        public string StatementTypeCode { get; set; }
        public string ExternalSourceName { get; set; }
        public string ComTypeCode { get; set; }
        public bool? IsConsolidated { get; set; }
        public bool? IsAudit { get; set; }
        public bool? IsDirect { get; set; }
        public decimal? NumberOfEmployee { get; set; }
        public decimal? BSA1 { get; set; }
        public decimal? BSA2 { get; set; }
        public decimal? BSA3 { get; set; }
        public decimal? BSA4 { get; set; }
        public decimal? BSA5 { get; set; }
        public decimal? BSA6 { get; set; }
        public decimal? BSA7 { get; set; }
        public decimal? BSA8 { get; set; }
        public decimal? BSA9 { get; set; }
        public decimal? BSA10 { get; set; }
        public decimal? BSA11 { get; set; }
        public decimal? BSA12 { get; set; }
        public decimal? BSA13 { get; set; }
        public decimal? BSA14 { get; set; }
        public decimal? BSA15 { get; set; }
        public decimal? BSA16 { get; set; }
        public decimal? BSA17 { get; set; }
        public decimal? BSA18 { get; set; }
        public decimal? BSA19 { get; set; }
        public decimal? BSA20 { get; set; }
        public decimal? BSA21 { get; set; }
        public decimal? BSA22 { get; set; }
        public decimal? BSA23 { get; set; }
        public decimal? BSA24 { get; set; }
        public decimal? BSA25 { get; set; }
        public decimal? BSA26 { get; set; }
        public decimal? BSA27 { get; set; }
        public decimal? BSA28 { get; set; }
        public decimal? BSA29 { get; set; }
        public decimal? BSA30 { get; set; }
        public decimal? BSA31 { get; set; }
        public decimal? BSA32 { get; set; }
        public decimal? BSA33 { get; set; }
        public decimal? BSA34 { get; set; }
        public decimal? BSA35 { get; set; }
        public decimal? BSA36 { get; set; }
        public decimal? BSA37 { get; set; }
        public decimal? BSA38 { get; set; }
        public decimal? BSA39 { get; set; }
        public decimal? BSA40 { get; set; }
        public decimal? BSA41 { get; set; }
        public decimal? BSA42 { get; set; }
        public decimal? BSA43 { get; set; }
        public decimal? BSA44 { get; set; }
        public decimal? BSA45 { get; set; }
        public decimal? BSA46 { get; set; }
        public decimal? BSA47 { get; set; }
        public decimal? BSA48 { get; set; }
        public decimal? BSA49 { get; set; }
        public decimal? BSA50 { get; set; }
        public decimal? BSA51 { get; set; }
        public decimal? BSA52 { get; set; }
        public decimal? BSA53 { get; set; }
        public decimal? BSA54 { get; set; }
        public decimal? BSA55 { get; set; }
        public decimal? BSA56 { get; set; }
        public decimal? BSA57 { get; set; }
        public decimal? BSA58 { get; set; }
        public decimal? BSA59 { get; set; }
        public decimal? BSA60 { get; set; }
        public decimal? BSA61 { get; set; }
        public decimal? BSA62 { get; set; }
        public decimal? BSA63 { get; set; }
        public decimal? BSA64 { get; set; }
        public decimal? BSA65 { get; set; }
        public decimal? BSA66 { get; set; }
        public decimal? BSA67 { get; set; }
        public decimal? BSA68 { get; set; }
        public decimal? BSA69 { get; set; }
        public decimal? BSA70 { get; set; }
        public decimal? BSA71 { get; set; }
        public decimal? BSA72 { get; set; }
        public decimal? BSA73 { get; set; }
        public decimal? BSA74 { get; set; }
        public decimal? BSA75 { get; set; }
        public decimal? BSA76 { get; set; }
        public decimal? BSA77 { get; set; }
        public decimal? BSA78 { get; set; }
        public decimal? BSA79 { get; set; }
        public decimal? BSA80 { get; set; }
        public decimal? BSA81 { get; set; }
        public decimal? BSA82 { get; set; }
        public decimal? BSA83 { get; set; }
        public decimal? BSA84 { get; set; }
        public decimal? BSA85 { get; set; }
        public decimal? BSA86 { get; set; }
        public decimal? BSA87 { get; set; }
        public decimal? BSA88 { get; set; }
        public decimal? BSA89 { get; set; }
        public decimal? BSA90 { get; set; }
        public decimal? BSA91 { get; set; }
        public decimal? BSA92 { get; set; }
        public decimal? BSA93 { get; set; }
        public decimal? BSA94 { get; set; }
        public decimal? BSA95 { get; set; }
        public decimal? BSA96 { get; set; }
        public decimal? BSB97 { get; set; }
        public decimal? BSB98 { get; set; }
        public decimal? BSB99 { get; set; }
        public decimal? BSB100 { get; set; }
        public decimal? BSB101 { get; set; }
        public decimal? BSB102 { get; set; }
        public decimal? BSB103 { get; set; }
        public decimal? BSB104 { get; set; }
        public decimal? BSB105 { get; set; }
        public decimal? BSB106 { get; set; }
        public decimal? BSB107 { get; set; }
        public decimal? BSB108 { get; set; }
        public decimal? BSB109 { get; set; }
        public decimal? BSB110 { get; set; }
        public decimal? BSB111 { get; set; }
        public decimal? BSB112 { get; set; }
        public decimal? BSB113 { get; set; }
        public decimal? BSB114 { get; set; }
        public decimal? BSB115 { get; set; }
        public decimal? BSB116 { get; set; }
        public decimal? BSB117 { get; set; }
        public decimal? BSB118 { get; set; }
        public decimal? BSB119 { get; set; }
        public decimal? BSB120 { get; set; }
        public decimal? BSB121 { get; set; }
        public decimal? BSB122 { get; set; }
        public decimal? BSB123 { get; set; }
        public decimal? BSB124 { get; set; }
        public decimal? BSB125 { get; set; }
        public decimal? BSB126 { get; set; }
        public decimal? BSB127 { get; set; }
        public decimal? BSB128 { get; set; }
        public decimal? BSB129 { get; set; }
        public decimal? BSB130 { get; set; }
        public decimal? BSB131 { get; set; }
        public decimal? BSB132 { get; set; }
        public decimal? BSS133 { get; set; }
        public decimal? BSS134 { get; set; }
        public decimal? BSS135 { get; set; }
        public decimal? BSS136 { get; set; }
        public decimal? BSS137 { get; set; }
        public decimal? BSS138 { get; set; }
        public decimal? BSI139 { get; set; }
        public decimal? BSI140 { get; set; }
        public decimal? BSI141 { get; set; }
        public decimal? BSI142 { get; set; }
        public decimal? BSI143 { get; set; }
        public decimal? BSI144 { get; set; }
        public decimal? BSI145 { get; set; }
        public decimal? BSI146 { get; set; }
        public decimal? BSI147 { get; set; }
        public decimal? BSI148 { get; set; }
        public decimal? BSI149 { get; set; }
        public decimal? BSI150 { get; set; }
        public decimal? BSI151 { get; set; }
        public decimal? BSI152 { get; set; }
        public decimal? BSI153 { get; set; }
        public decimal? BSI154 { get; set; }
        public decimal? BSI155 { get; set; }
        public decimal? BSI156 { get; set; }
        public decimal? BSB157 { get; set; }
        public decimal? BSB158 { get; set; }
        public decimal? BSA159 { get; set; }
        public decimal? BSA160 { get; set; }
        public decimal? BSA161 { get; set; }
        public decimal? BSA162 { get; set; }
        public decimal? BSA163 { get; set; }
        public decimal? BSA164 { get; set; }
        public decimal? BSA165 { get; set; }
        public decimal? BSA166 { get; set; }
        public decimal? BSA167 { get; set; }
        public decimal? BSA168 { get; set; }
        public decimal? BSA169 { get; set; }
        public decimal? BSA170 { get; set; }
        public decimal? BSA171 { get; set; }
        public decimal? BSA172 { get; set; }
        public decimal? BSA173 { get; set; }
        public decimal? BSA174 { get; set; }
        public decimal? BSA175 { get; set; }
        public decimal? BSA176 { get; set; }
        public decimal? BSA177 { get; set; }
        public decimal? BSA178 { get; set; }
        public decimal? BSB179 { get; set; }
        public decimal? BSB180 { get; set; }
        public decimal? BSB181 { get; set; }
        public decimal? BSB182 { get; set; }
        public decimal? BSB183 { get; set; }
        public decimal? BSB184 { get; set; }
        public decimal? BSB185 { get; set; }
        public decimal? BSB186 { get; set; }
        public decimal? BSS187 { get; set; }
        public decimal? BSA188 { get; set; }
        public decimal? BSS189 { get; set; }
        public decimal? BSI190 { get; set; }
        public decimal? BSI191 { get; set; }
        public decimal? BSI192 { get; set; }
        public decimal? BSI193 { get; set; }
        public decimal? BSI194 { get; set; }
        public decimal? BSI195 { get; set; }
        public decimal? BSI196 { get; set; }
        public decimal? BSI197 { get; set; }
        public decimal? BSI198 { get; set; }
        public decimal? BSI199 { get; set; }
        public decimal? BSI200 { get; set; }
        public decimal? BSI201 { get; set; }
        public decimal? BSI202 { get; set; }
        public decimal? BSI203 { get; set; }
        public decimal? BSI204 { get; set; }
        public decimal? BSI205 { get; set; }
        public decimal? BSI206 { get; set; }
        public decimal? BSI207 { get; set; }
        public decimal? BSI208 { get; set; }
        public decimal? BSA209 { get; set; }
        public decimal? BSA210 { get; set; }
        public decimal? BSA211 { get; set; }
        public decimal? BSS212 { get; set; }
        public decimal? BSS213 { get; set; }
        public decimal? BSS214 { get; set; }
        public decimal? BSS215 { get; set; }
        public decimal? BSS216 { get; set; }
        public decimal? BSS217 { get; set; }
        public decimal? BSS218 { get; set; }
        public decimal? BSS219 { get; set; }
        public decimal? BSS220 { get; set; }
        public decimal? BSS221 { get; set; }
        public decimal? BSS222 { get; set; }
        public decimal? BSS223 { get; set; }
        public decimal? BSS224 { get; set; }
        public decimal? BSS225 { get; set; }
        public decimal? BSS226 { get; set; }
        public decimal? BSS227 { get; set; }
        public decimal? BSS228 { get; set; }
        public decimal? BSS229 { get; set; }
        public decimal? BSS230 { get; set; }
        public decimal? BSS231 { get; set; }
        public decimal? BSS232 { get; set; }
        public decimal? BSS233 { get; set; }
        public decimal? BSS234 { get; set; }
        public decimal? BSS235 { get; set; }
        public decimal? BSS236 { get; set; }
        public decimal? BSS237 { get; set; }
        public decimal? BSS238 { get; set; }
        public decimal? BSS239 { get; set; }
        public decimal? BSS240 { get; set; }
        public decimal? BSS241 { get; set; }
        public decimal? BSS242 { get; set; }
        public decimal? BSS243 { get; set; }
        public decimal? BSS244 { get; set; }
        public decimal? BSS245 { get; set; }
        public decimal? BSS246 { get; set; }
        public decimal? BSS247 { get; set; }
        public decimal? BSS248 { get; set; }
        public decimal? BSS249 { get; set; }
        public decimal? BSS250 { get; set; }
        public decimal? BSS251 { get; set; }
        public decimal? BSS252 { get; set; }
        public decimal? BSS253 { get; set; }
        public decimal? BSS254 { get; set; }
        public decimal? BSS255 { get; set; }
        public decimal? BSS256 { get; set; }
        public decimal? BSS257 { get; set; }
        public decimal? BSMS1 { get; set; }
        public decimal? BSMS2 { get; set; }
        public decimal? BSMS3 { get; set; }
        public decimal? BSMS4 { get; set; }
        public decimal? BSMS5 { get; set; }
        public decimal? BSMS6 { get; set; }
        public decimal? BSMS7 { get; set; }
        public decimal? BSMS8 { get; set; }
        public decimal? BSMS9 { get; set; }
        public decimal? BSMS10 { get; set; }
        public decimal? BSMS11 { get; set; }
        public decimal? BSMS12 { get; set; }
        public decimal? BSMS13 { get; set; }
        public decimal? BSMS14 { get; set; }
        public decimal? BSMS15 { get; set; }
        public decimal? BSMS16 { get; set; }
        public decimal? BSMS17 { get; set; }
        public decimal? BSMS18 { get; set; }
        public decimal? BSMS19 { get; set; }
        public decimal? BSMS20 { get; set; }
        public decimal? BSMS21 { get; set; }
        public decimal? BSMS22 { get; set; }
        public decimal? BSMS23 { get; set; }
        public decimal? BSMS24 { get; set; }
        public decimal? BSMS25 { get; set; }
        public decimal? BSMS26 { get; set; }
        public decimal? BSMS27 { get; set; }
        public decimal? BSMS28 { get; set; }
        public decimal? BSMS29 { get; set; }
        public decimal? BSMS30 { get; set; }
        public decimal? BSMS31 { get; set; }
        public decimal? BSMS32 { get; set; }
        public decimal? BSMS33 { get; set; }
        public decimal? BSMS34 { get; set; }
        public decimal? BSMS35 { get; set; }
        public decimal? BSMS36 { get; set; }
        public decimal? BSMS37 { get; set; }
        public decimal? BSMS38 { get; set; }
        public decimal? BSMS39 { get; set; }
        public decimal? BSMS40 { get; set; }
        public decimal? BSMS41 { get; set; }
        public decimal? BSMS42 { get; set; }
        public decimal? BSMS43 { get; set; }
        public decimal? BSMS44 { get; set; }
        public decimal? BSMS45 { get; set; }
        public decimal? BSA278 { get; set; }
        public decimal? BSNB1 { get; set; }
        public decimal? BSNB2 { get; set; }
        public decimal? BSNB3 { get; set; }
        public decimal? BSNB4 { get; set; }
        public decimal? BSNB5 { get; set; }
        public decimal? BSNB6 { get; set; }
        public decimal? BSNB7 { get; set; }
        public decimal? BSNB8 { get; set; }
        public decimal? BSNB9 { get; set; }
        public decimal? BSNB10 { get; set; }
        public decimal? BSNB11 { get; set; }
        public decimal? BSNB12 { get; set; }
        public decimal? BSNB13 { get; set; }
        public decimal? BSNB14 { get; set; }
        public decimal? BSNB15 { get; set; }
        public decimal? BSNB16 { get; set; }
        public decimal? BSNB17 { get; set; }
        public decimal? BSNB18 { get; set; }
        public decimal? BSNB19 { get; set; }
        public decimal? BSB258 { get; set; }
        public decimal? BSB259 { get; set; }
        public decimal? BSB260 { get; set; }
        public decimal? BSB261 { get; set; }
        public decimal? BSB262 { get; set; }
        public decimal? BSB263 { get; set; }
        public decimal? BSB264 { get; set; }
        public decimal? BSB265 { get; set; }
        public decimal? BSB266 { get; set; }
        public decimal? BSB267 { get; set; }
        public decimal? BSB268 { get; set; }
        public decimal? BSB269 { get; set; }
        public decimal? BSB270 { get; set; }
        public decimal? BSB271 { get; set; }
        public decimal? BSB272 { get; set; }
        public decimal? BSB273 { get; set; }
        public decimal? BSB274 { get; set; }
        public decimal? BSB275 { get; set; }
        public decimal? BSA276 { get; set; }
        public decimal? BSA277 { get; set; }
        public decimal? BSI279 { get; set; }
        public decimal? BSI280 { get; set; }
        public decimal? BSI281 { get; set; }
        public decimal? BSI282 { get; set; }
        public decimal? BSI283 { get; set; }
        public decimal? BSI284 { get; set; }
        public decimal? BSI285 { get; set; }
        public decimal? BSI286 { get; set; }
        public decimal? BSI287 { get; set; }
        public decimal? ISA1 { get; set; }
        public decimal? ISA2 { get; set; }
        public decimal? ISA3 { get; set; }
        public decimal? ISA4 { get; set; }
        public decimal? ISA5 { get; set; }
        public decimal? ISA6 { get; set; }
        public decimal? ISA7 { get; set; }
        public decimal? ISA8 { get; set; }
        public decimal? ISA9 { get; set; }
        public decimal? ISA10 { get; set; }
        public decimal? ISA11 { get; set; }
        public decimal? ISA12 { get; set; }
        public decimal? ISA13 { get; set; }
        public decimal? ISA14 { get; set; }
        public decimal? ISA15 { get; set; }
        public decimal? ISA16 { get; set; }
        public decimal? ISA17 { get; set; }
        public decimal? ISA18 { get; set; }
        public decimal? ISA19 { get; set; }
        public decimal? ISA20 { get; set; }
        public decimal? ISA21 { get; set; }
        public decimal? ISA22 { get; set; }
        public decimal? ISA23 { get; set; }
        public decimal? ISA24 { get; set; }
        public decimal? ISB25 { get; set; }
        public decimal? ISB26 { get; set; }
        public decimal? ISB27 { get; set; }
        public decimal? ISB28 { get; set; }
        public decimal? ISB29 { get; set; }
        public decimal? ISB30 { get; set; }
        public decimal? ISB31 { get; set; }
        public decimal? ISB32 { get; set; }
        public decimal? ISB33 { get; set; }
        public decimal? ISB34 { get; set; }
        public decimal? ISB35 { get; set; }
        public decimal? ISB36 { get; set; }
        public decimal? ISB37 { get; set; }
        public decimal? ISB38 { get; set; }
        public decimal? ISB39 { get; set; }
        public decimal? ISB40 { get; set; }
        public decimal? ISB41 { get; set; }
        public decimal? ISS42 { get; set; }
        public decimal? ISS43 { get; set; }
        public decimal? ISS44 { get; set; }
        public decimal? ISS45 { get; set; }
        public decimal? ISS46 { get; set; }
        public decimal? ISS47 { get; set; }
        public decimal? ISS48 { get; set; }
        public decimal? ISS49 { get; set; }
        public decimal? ISS50 { get; set; }
        public decimal? ISI51 { get; set; }
        public decimal? ISI52 { get; set; }
        public decimal? ISI53 { get; set; }
        public decimal? ISI54 { get; set; }
        public decimal? ISI55 { get; set; }
        public decimal? ISI56 { get; set; }
        public decimal? ISI57 { get; set; }
        public decimal? ISI58 { get; set; }
        public decimal? ISI59 { get; set; }
        public decimal? ISI60 { get; set; }
        public decimal? ISI61 { get; set; }
        public decimal? ISI62 { get; set; }
        public decimal? ISI63 { get; set; }
        public decimal? ISI64 { get; set; }
        public decimal? ISI65 { get; set; }
        public decimal? ISI66 { get; set; }
        public decimal? ISI67 { get; set; }
        public decimal? ISI68 { get; set; }
        public decimal? ISI69 { get; set; }
        public decimal? ISI70 { get; set; }
        public decimal? ISI71 { get; set; }
        public decimal? ISI72 { get; set; }
        public decimal? ISI73 { get; set; }
        public decimal? ISI74 { get; set; }
        public decimal? ISI75 { get; set; }
        public decimal? ISI76 { get; set; }
        public decimal? ISI77 { get; set; }
        public decimal? ISI78 { get; set; }
        public decimal? ISI79 { get; set; }
        public decimal? ISI80 { get; set; }
        public decimal? ISI81 { get; set; }
        public decimal? ISI82 { get; set; }
        public decimal? ISI83 { get; set; }
        public decimal? ISI84 { get; set; }
        public decimal? ISI85 { get; set; }
        public decimal? ISI86 { get; set; }
        public decimal? ISI87 { get; set; }
        public decimal? ISI88 { get; set; }
        public decimal? ISI89 { get; set; }
        public decimal? ISI90 { get; set; }
        public decimal? ISI91 { get; set; }
        public decimal? ISI92 { get; set; }
        public decimal? ISI93 { get; set; }
        public decimal? ISI94 { get; set; }
        public decimal? ISI95 { get; set; }
        public decimal? ISI96 { get; set; }
        public decimal? ISI97 { get; set; }
        public decimal? ISI98 { get; set; }
        public decimal? ISI99 { get; set; }
        public decimal? ISI100 { get; set; }
        public decimal? ISI101 { get; set; }
        public decimal? ISA102 { get; set; }
        public decimal? ISI103 { get; set; }
        public decimal? ISI104 { get; set; }
        public decimal? ISI105 { get; set; }
        public decimal? ISI106 { get; set; }
        public decimal? ISI107 { get; set; }
        public decimal? ISI108 { get; set; }
        public decimal? ISI109 { get; set; }
        public decimal? ISI110 { get; set; }
        public decimal? ISI111 { get; set; }
        public decimal? ISI112 { get; set; }
        public decimal? ISI113 { get; set; }
        public decimal? ISI114 { get; set; }
        public decimal? ISS115 { get; set; }
        public decimal? ISS116 { get; set; }
        public decimal? ISS117 { get; set; }
        public decimal? ISS118 { get; set; }
        public decimal? ISS119 { get; set; }
        public decimal? ISS120 { get; set; }
        public decimal? ISS121 { get; set; }
        public decimal? ISS122 { get; set; }
        public decimal? ISS123 { get; set; }
        public decimal? ISS124 { get; set; }
        public decimal? ISS125 { get; set; }
        public decimal? ISS126 { get; set; }
        public decimal? ISS127 { get; set; }
        public decimal? ISS128 { get; set; }
        public decimal? ISS129 { get; set; }
        public decimal? ISS130 { get; set; }
        public decimal? ISS168 { get; set; }
        public decimal? ISS131 { get; set; }
        public decimal? ISS132 { get; set; }
        public decimal? ISS133 { get; set; }
        public decimal? ISS134 { get; set; }
        public decimal? ISS135 { get; set; }
        public decimal? ISS136 { get; set; }
        public decimal? ISS137 { get; set; }
        public decimal? ISS138 { get; set; }
        public decimal? ISS139 { get; set; }
        public decimal? ISS140 { get; set; }
        public decimal? ISS141 { get; set; }
        public decimal? ISS142 { get; set; }
        public decimal? ISS143 { get; set; }
        public decimal? ISS144 { get; set; }
        public decimal? ISS145 { get; set; }
        public decimal? ISS146 { get; set; }
        public decimal? ISS147 { get; set; }
        public decimal? ISS148 { get; set; }
        public decimal? ISS149 { get; set; }
        public decimal? ISS150 { get; set; }
        public decimal? ISS151 { get; set; }
        public decimal? ISS152 { get; set; }
        public decimal? ISS153 { get; set; }
        public decimal? ISS154 { get; set; }
        public decimal? ISS155 { get; set; }
        public decimal? ISS156 { get; set; }
        public decimal? ISS157 { get; set; }
        public decimal? ISS158 { get; set; }
        public decimal? ISS159 { get; set; }
        public decimal? ISS160 { get; set; }
        public decimal? ISS161 { get; set; }
        public decimal? ISS162 { get; set; }
        public decimal? ISS163 { get; set; }
        public decimal? ISS164 { get; set; }
        public decimal? ISS165 { get; set; }
        public decimal? ISS166 { get; set; }
        public decimal? ISS167 { get; set; }
        public decimal? ISMS1 { get; set; }
        public decimal? CFA1 { get; set; }
        public decimal? CFA2 { get; set; }
        public decimal? CFA3 { get; set; }
        public decimal? CFA4 { get; set; }
        public decimal? CFA5 { get; set; }
        public decimal? CFA6 { get; set; }
        public decimal? CFA7 { get; set; }
        public decimal? CFA8 { get; set; }
        public decimal? CFA9 { get; set; }
        public decimal? CFA10 { get; set; }
        public decimal? CFA11 { get; set; }
        public decimal? CFA12 { get; set; }
        public decimal? CFA13 { get; set; }
        public decimal? CFA14 { get; set; }
        public decimal? CFA15 { get; set; }
        public decimal? CFA16 { get; set; }
        public decimal? CFA17 { get; set; }
        public decimal? CFA18 { get; set; }
        public decimal? CFA19 { get; set; }
        public decimal? CFA20 { get; set; }
        public decimal? CFA21 { get; set; }
        public decimal? CFA22 { get; set; }
        public decimal? CFA23 { get; set; }
        public decimal? CFA24 { get; set; }
        public decimal? CFA25 { get; set; }
        public decimal? CFA26 { get; set; }
        public decimal? CFA27 { get; set; }
        public decimal? CFA28 { get; set; }
        public decimal? CFA29 { get; set; }
        public decimal? CFA30 { get; set; }
        public decimal? CFA31 { get; set; }
        public decimal? CFA32 { get; set; }
        public decimal? CFA33 { get; set; }
        public decimal? CFA34 { get; set; }
        public decimal? CFA35 { get; set; }
        public decimal? CFA36 { get; set; }
        public decimal? CFA37 { get; set; }
        public decimal? CFA38 { get; set; }
        public decimal? CFA39 { get; set; }
        public decimal? CFA40 { get; set; }
        public decimal? CFA41 { get; set; }
        public decimal? CFA42 { get; set; }
        public decimal? CFA43 { get; set; }
        public decimal? CFA44 { get; set; }
        public decimal? CFA45 { get; set; }
        public decimal? CFB46 { get; set; }
        public decimal? CFB47 { get; set; }
        public decimal? CFB48 { get; set; }
        public decimal? CFB49 { get; set; }
        public decimal? CFB50 { get; set; }
        public decimal? CFB51 { get; set; }
        public decimal? CFB52 { get; set; }
        public decimal? CFB53 { get; set; }
        public decimal? CFB54 { get; set; }
        public decimal? CFB55 { get; set; }
        public decimal? CFB56 { get; set; }
        public decimal? CFB57 { get; set; }
        public decimal? CFB58 { get; set; }
        public decimal? CFB59 { get; set; }
        public decimal? CFB60 { get; set; }
        public decimal? CFB61 { get; set; }
        public decimal? CFB62 { get; set; }
        public decimal? CFB63 { get; set; }
        public decimal? CFB64 { get; set; }
        public decimal? CFB65 { get; set; }
        public decimal? CFB66 { get; set; }
        public decimal? CFB67 { get; set; }
        public decimal? CFB68 { get; set; }
        public decimal? CFB69 { get; set; }
        public decimal? CFB70 { get; set; }
        public decimal? CFB71 { get; set; }
        public decimal? CFB72 { get; set; }
        public decimal? CFB73 { get; set; }
        public decimal? CFB74 { get; set; }
        public decimal? CFB75 { get; set; }
        public decimal? CFB76 { get; set; }
        public decimal? CFB77 { get; set; }
        public decimal? CFB78 { get; set; }
        public decimal? CFB79 { get; set; }
        public decimal? CFB80 { get; set; }
        public decimal? CFB81 { get; set; }
        public decimal? CFS82 { get; set; }
        public decimal? CFS83 { get; set; }
        public decimal? CFS84 { get; set; }
        public decimal? CFS85 { get; set; }
        public decimal? CFS86 { get; set; }
        public decimal? CFS87 { get; set; }
        public decimal? CFS88 { get; set; }
        public decimal? CFI89 { get; set; }
        public decimal? CFI90 { get; set; }
        public decimal? CFI91 { get; set; }
        public decimal? CFI92 { get; set; }
        public decimal? CFI93 { get; set; }
        public decimal? CFI94 { get; set; }
        public decimal? CFI95 { get; set; }
        public decimal? CFI96 { get; set; }
        public decimal? CFI97 { get; set; }
        public decimal? CFI98 { get; set; }
        public decimal? CFI99 { get; set; }
        public decimal? CFI100 { get; set; }
        public decimal? CFI101 { get; set; }
        public decimal? CFI102 { get; set; }
        public decimal? CFA103 { get; set; }
        public decimal? CFA104 { get; set; }
        public decimal? CFA105 { get; set; }
        public decimal? CFB106 { get; set; }
        public decimal? CFS107 { get; set; }
        public decimal? CFS108 { get; set; }
        public decimal? CFS109 { get; set; }
        public decimal? CFS110 { get; set; }
        public decimal? CFS111 { get; set; }
        public decimal? CFS112 { get; set; }
        public decimal? CFS113 { get; set; }
        public decimal? CFS114 { get; set; }
        public decimal? CFS115 { get; set; }
        public decimal? CFS116 { get; set; }
        public decimal? CFS117 { get; set; }
        public decimal? CFS118 { get; set; }
        public decimal? CFS119 { get; set; }
        public decimal? CFS120 { get; set; }
        public decimal? CFS121 { get; set; }
        public decimal? CFS122 { get; set; }
        public decimal? CFS123 { get; set; }
        public decimal? CFS124 { get; set; }
        public decimal? CFS125 { get; set; }
        public decimal? CFS126 { get; set; }
        public decimal? CFS127 { get; set; }
        public decimal? CFS128 { get; set; }
        public decimal? CFS129 { get; set; }
        public decimal? CFS130 { get; set; }
        public decimal? CFS131 { get; set; }
        public decimal? CFS132 { get; set; }
        public decimal? CFS133 { get; set; }
        public decimal? CFS134 { get; set; }
        public decimal? CFS135 { get; set; }
        public decimal? CFS136 { get; set; }
        public decimal? CFS137 { get; set; }
        public decimal? CFS138 { get; set; }
        public decimal? CFS139 { get; set; }
        public decimal? CFS140 { get; set; }
        public decimal? CFS141 { get; set; }
        public decimal? CFS142 { get; set; }
        public decimal? CFS143 { get; set; }
        public decimal? CFS144 { get; set; }
        public decimal? CFS145 { get; set; }
        public decimal? CFS146 { get; set; }
        public decimal? CFS147 { get; set; }
        public decimal? CFS148 { get; set; }
        public decimal? CFS149 { get; set; }
        public decimal? CFS150 { get; set; }
        public decimal? CFS151 { get; set; }
        public decimal? CFS152 { get; set; }
        public decimal? CFS153 { get; set; }
        public decimal? CFS154 { get; set; }
        public decimal? CFS155 { get; set; }
        public decimal? CFS156 { get; set; }
        public decimal? CFS157 { get; set; }
        public decimal? CFS158 { get; set; }
        public decimal? CFS159 { get; set; }
        public decimal? CFS160 { get; set; }
        public decimal? CFS161 { get; set; }
        public decimal? CFS162 { get; set; }
        public decimal? CFS163 { get; set; }
        public decimal? CFS164 { get; set; }
        public decimal? CFS165 { get; set; }
        public decimal? CFS166 { get; set; }
        public decimal? CFS167 { get; set; }
        public decimal? CFS168 { get; set; }
        public decimal? CFS169 { get; set; }
        public decimal? CFS170 { get; set; }
        public decimal? CFS171 { get; set; }
        public decimal? CFS172 { get; set; }
        public decimal? CFS173 { get; set; }
        public decimal? CFS174 { get; set; }
        public decimal? CFS175 { get; set; }
        public decimal? CFS176 { get; set; }
        public decimal? CFS177 { get; set; }
        public decimal? CFS178 { get; set; }
        public decimal? CFS179 { get; set; }
        public decimal? CFS180 { get; set; }
        public decimal? CFS181 { get; set; }
        public decimal? CFS182 { get; set; }
        public decimal? CFS183 { get; set; }
        public decimal? CFS184 { get; set; }
        public decimal? CFS185 { get; set; }
        public decimal? CFS186 { get; set; }
        public decimal? CFS187 { get; set; }
        public decimal? CFS188 { get; set; }
        public decimal? CFS189 { get; set; }
        public decimal? CFS190 { get; set; }
        public decimal? CFS191 { get; set; }
        public decimal? CFS192 { get; set; }
        public decimal? CFS193 { get; set; }
        public decimal? CFS194 { get; set; }
        public decimal? CFS195 { get; set; }
        public decimal? CFS196 { get; set; }
        public decimal? CFS197 { get; set; }
        public decimal? CFS198 { get; set; }
        public decimal? CFS199 { get; set; }
        public decimal? CFS200 { get; set; }
        public decimal? CFS201 { get; set; }
        public decimal? CFS202 { get; set; }
        public decimal? CFS203 { get; set; }
        public decimal? CFS204 { get; set; }
        public decimal? CFS205 { get; set; }
        public decimal? CFS206 { get; set; }
        public decimal? CFS207 { get; set; }
        public decimal? CFS208 { get; set; }
        public decimal? CFS209 { get; set; }
        public decimal? CFS210 { get; set; }
        public decimal? CFS211 { get; set; }
        public decimal? CFS212 { get; set; }
        public decimal? CFS213 { get; set; }
        public decimal? CFS214 { get; set; }
        public decimal? CFS215 { get; set; }
        public decimal? CFS216 { get; set; }
        public decimal? CFS217 { get; set; }
        public decimal? CFS218 { get; set; }
        public decimal? CFS219 { get; set; }
        public decimal? CFS220 { get; set; }
        public decimal? CFMS1 { get; set; }
        public decimal? CFB221 { get; set; }
        public decimal? CFS222 { get; set; }
        public decimal? CFS223 { get; set; }
        public decimal? CFS224 { get; set; }
        public decimal? CFS225 { get; set; }
    }
}
